const { google } = require('googleapis');
const { Jimp } = require('jimp');
const fs = require('fs');

async function report(sock, message, args) {
  const chatId = message.key.remoteJid;
  const date = args[0]; // Example: .report 13012026

  if (!date) {
    return sock.sendMessage(
      chatId, 
      { text: '❌ *USAGE:*\n.report DDMMYYYY\nExample: `.report 02022026`' }, 
      { quoted: message }
    );
  }

  // Environment Variables se data lena
  const FOLDER_ID = process.env.DRIVE_FOLDER_ID;
  const GOOGLE_KEY = process.env.GOOGLE_DRIVE_KEY;

  if (!FOLDER_ID || !GOOGLE_KEY) {
    return sock.sendMessage(chatId, { text: '⚠️ Drive API keys are missing in Environment Variables.' });
  }

  try {
    // Google Drive Authentication
    const driveAuth = new google.auth.GoogleAuth({
      credentials: JSON.parse(GOOGLE_KEY),
      scopes: ['https://www.googleapis.com/auth/drive.readonly']
    });
    const drive = google.drive({ version: 'v3', auth: driveAuth });

    await sock.sendMessage(chatId, { text: `🔍 Searching Drive for: ${date}.png...` }, { quoted: message });

    // File find karna
    const res = await drive.files.list({
      q: `'${FOLDER_ID}' in parents and name = '${date}.png' and trashed = false`,
      fields: 'files(id, name)'
    });

    if (res.data.files.length > 0) {
      // File download karna
      const fileId = res.data.files[0].id;
      const imgRes = await drive.files.get(
        { fileId: fileId, alt: 'media' }, 
        { responseType: 'arraybuffer' }
      );

      let mainImg = await Jimp.read(Buffer.from(imgRes.data));

      // Logo Watermark lagana (agar logo.png root folder mein hai)
      if (fs.existsSync('./logo.png')) {
        const logo = await Jimp.read('./logo.png');
        logo.resize({ w: 150 });
        // Bottom-right corner mein position karna
        mainImg.composite(logo, mainImg.width - 170, mainImg.height - 100);
      }

      const buffer = await mainImg.getBuffer('image/png');

      await sock.sendMessage(
        chatId, 
        { image: buffer, caption: `✅ *GENERATED BY HAFEEZ*\n📅 Date: ${date}` }, 
        { quoted: message }
      );

    } else {
      await sock.sendMessage(chatId, { text: `❌ Report not found for *${date}*.\REPORT \`${date} \`NOT UPLOADED.` });
    }
  } catch (error) {
    console.error("Drive Error:", error);
    await sock.sendMessage(chatId, { text: '⚠️ *Error:* ' + error.message });
  }
}

module.exports = { report };
